# name: Deploy to EC2

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SSH_KEY }}
#           aws-region: ap-northeast-2

#       - name: Deploy Frontend
#         run: |
#           # 프론트엔드 빌드
#           cd frontend
#           npm install
#           npm run build
          
#           # 빌드된 파일을 EC2에 업로드
#           scp -r build/* ubuntu@${{ secrets.EC2_HOST }}:/usr/share/nginx/react_flask_image_bgremove/frontend/build/
          
#           # Nginx 설정 업데이트
#           ssh ubuntu@${{ secrets.EC2_HOST }} 'sudo systemctl restart nginx'

#       - name: Deploy Backend
#         run: |
#           # 백엔드 파일을 EC2에 업로드
#           scp -r backend/* ubuntu@${{ secrets.EC2_HOST }}:/usr/share/nginx/react_flask_image_bgremove/backend/
          
#           # EC2에서 백엔드 서비스 재시작
#           ssh ubuntu@${{ secrets.EC2_HOST }} '
#             cd /usr/share/nginx/react_flask_image_bgremove/backend
#             source venv/bin/activate
#             pip install -r requirements.txt
#             sudo systemctl restart flask-app
#           ' 